---
AWSTemplateFormatVersion: '2010-09-09'
Description: CrowdStrike Cloud-Security (CSPM) Registration Template for Control Tower

Parameters:
  StackSetExecRole:
    Description: Execution Role for CrowdStrike StackSet
    Type: String
    Default: 'CrowdStrikeStackSetExecutionRole'
  StackSetAdminRole:
    Description: Administration Role for CrowdStrike StackSet
    Type: String
    Default: ''

Resources:
  # IAM Role to allow StackSet Execution
  StackSetExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref StackSetExecRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Action: sts:AssumeRole
          Principal:
            AWS: !Ref StackSetAdminRole
          Effect: Allow
          Sid: ''
      Policies:
        - PolicyName: crowdstrike-stackset-execution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - events:DeleteRule
                - events:PutTargets
                - events:DescribeRule
                - iam:PassRole
                - events:EnableRule
                - events:PutRule
                - events:RemoveTargets
                - events:DisableRule
                Resource:
                - !Sub arn:${AWS::Partition}:events:*:*:rule/cs-*
                - !Sub arn:${AWS::Partition}:events:*:*:rule/*/cs-*
                - !Sub arn:${AWS::Partition}:iam::*:role/CrowdStrike*
                Effect: Allow
              - Action: cloudformation:*
                Resource: '*'
                Effect: Allow
              - Action:
                - iam:GetRole
                - iam:CreateRole
                - iam:DeleteRole
                - iam:CreatePolicy
                - iam:DeletePolicy
                - iam:PutRolePolicy
                - iam:DeleteRolePolicy
                - iam:DetachRolePolicy
                - iam:AttachRolePolicy
                Resource: '*'
                Effect: Allow
              - Action:
                - lambda:CreateFunction
                - lambda:DeleteFunction
                - lambda:CreateAlias
                - lambda:DeleteAlias
                - lambda:AddPermission
                - lambda:RemovePermission
                - lambda:InvokeFunction
                - lambda:GetFunction
                Resource: '*'
                Effect: Allow
              - Action:
                - logs:CreateLogGroup
                - logs:DeleteLogGroup
                - logs:PutRetentionPolicy
                - logs:DeleteRetentionPolicy
                Resource: '*'
                Effect: Allow
              - Action:
                - s3:GetObject
                - s3:DeleteObject
                - s3:PutObject
                - s3:CreateBucket
                - s3:DeleteBucket
                - s3:PutBucketPolicy
                - s3:DeleteBucketPolicy
                Resource: '*'
                Effect: Allow