---
AWSTemplateFormatVersion: '2010-09-09'
Description: CrowdStrike Cloud-Security (CSPM) Registration Template for registration to multiple Falcon CIDs
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: CID A
        Parameters:
          - OUA
          - FalconClientIdA
          - FalconSecretA
          - FalconCloudA
      - Label: 
          default: CID B
        Parameters:
          - OUB
          - FalconClientIdB
          - FalconSecretB
          - FalconCloudB
      - Label: 
          default: CID C
        Parameters:
          - OUC
          - FalconClientIdC
          - FalconSecretC
          - FalconCloudC
      - Label: 
          default: CID D
        Parameters:
          - OUD
          - FalconClientIdD
          - FalconSecretD
          - FalconCloudD
      - Label: 
          default: CID E
        Parameters:
          - OUE
          - FalconClientIdE
          - FalconSecretE
          - FalconCloudE
      - Label: 
          default: CID F
        Parameters:
          - OUF
          - FalconClientIdF
          - FalconSecretF
          - FalconCloudF
      - Label: 
          default: CID G
        Parameters:
          - OUG
          - FalconClientIdG
          - FalconSecretG
          - FalconCloudG

Parameters:
  OUA:
    Description: Your AWS OU for FalconClientIdA & FalconSecretA.
    Type: String
    Default: ''
  FalconClientIdA:
    Description: Your CrowdStrike Falcon OAuth2 Client ID for OUA.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconSecretA:
    Description: Your CrowdStrike Falcon OAuth2 API Secret for OUA.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconCloudA:
    Description: Your CrowdStrike Falcon Cloud for OUA.
    Type: String
    Default: 'us1'
    AllowedValues:
      - 'us1'
      - 'us2'
      - 'eu1'
      - 'usgov1'
      - 'usgov2'
  OUB:
    Description: Your AWS OU for FalconClientIdB & FalconSecretB.
    Type: String
    Default: ''
  FalconClientIdB:
    Description: Your CrowdStrike Falcon OAuth2 Client ID for OUB.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconSecretB:
    Description: Your CrowdStrike Falcon OAuth2 API Secret for OUB.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconCloudB:
    Description: Your CrowdStrike Falcon Cloud for OUB.
    Type: String
    Default: 'us1'
    AllowedValues:
      - 'us1'
      - 'us2'
      - 'eu1'
      - 'usgov1'
      - 'usgov2'
  OUC:
    Description: Your AWS OU for FalconClientIdC & FalconSecretC.
    Type: String
    Default: ''
  FalconClientIdC:
    Description: Your CrowdStrike Falcon OAuth2 Client ID for OUC.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconSecretC:
    Description: Your CrowdStrike Falcon OAuth2 API Secret for OUC.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconCloudC:
    Description: Your CrowdStrike Falcon Cloud for OUC.
    Type: String
    Default: 'us1'
    AllowedValues:
      - 'us1'
      - 'us2'
      - 'eu1'
      - 'usgov1'
      - 'usgov2'
  OUD:
    Description: Your AWS OU for FalconClientIdC & FalconSecretC.
    Type: String
    Default: ''
  FalconClientIdD:
    Description: Your CrowdStrike Falcon OAuth2 Client ID for OUC.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconSecretD:
    Description: Your CrowdStrike Falcon OAuth2 API Secret for OUC.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconCloudD:
    Description: Your CrowdStrike Falcon Cloud for OUC.
    Type: String
    Default: 'us1'
    AllowedValues:
      - 'us1'
      - 'us2'
      - 'eu1'
      - 'usgov1'
      - 'usgov2'
  OUE:
    Description: Your AWS OU for FalconClientIdA & FalconSecretA.
    Type: String
    Default: ''
  FalconClientIdE:
    Description: Your CrowdStrike Falcon OAuth2 Client ID for OUA.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconSecretE:
    Description: Your CrowdStrike Falcon OAuth2 API Secret for OUA.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconCloudE:
    Description: Your CrowdStrike Falcon Cloud for OUA.
    Type: String
    Default: 'us1'
    AllowedValues:
      - 'us1'
      - 'us2'
      - 'eu1'
      - 'usgov1'
      - 'usgov2'
  OUF:
    Description: Your AWS OU for FalconClientIdB & FalconSecretB.
    Type: String
    Default: ''
  FalconClientIdF:
    Description: Your CrowdStrike Falcon OAuth2 Client ID for OUB.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconSecretF:
    Description: Your CrowdStrike Falcon OAuth2 API Secret for OUB.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconCloudF:
    Description: Your CrowdStrike Falcon Cloud for OUB.
    Type: String
    Default: 'us1'
    AllowedValues:
      - 'us1'
      - 'us2'
      - 'eu1'
      - 'usgov1'
      - 'usgov2'
  OUG:
    Description: Your AWS OU for FalconClientIdC & FalconSecretC.
    Type: String
    Default: ''
  FalconClientIdG:
    Description: Your CrowdStrike Falcon OAuth2 Client ID for OUC.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconSecretG:
    Description: Your CrowdStrike Falcon OAuth2 API Secret for OUC.
    NoEcho: 'true'
    Type: String
    Default: ''
  FalconCloudG:
    Description: Your CrowdStrike Falcon Cloud for OUC.
    Type: String
    Default: 'us1'
    AllowedValues:
      - 'us1'
      - 'us2'
      - 'eu1'
      - 'usgov1'
      - 'usgov2'

Resources:
  # Create Secrets for registration lambda
  CrowdStrikeSecretA:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CrowdStrike Credentials
      Name: !Join
        - '-'
        - - CrowdStrikeAPISecret
          - !Ref OUA
      SecretString:
        Fn::Join:
          - ''
          - - '{"FalconClientId":"'
            - Ref: "FalconClientIdA"
            - '","FalconSecret": "'
            - Ref: FalconSecretA
            - '","FalconCloud": "'
            - Ref: FalconCloudA
            - '"}'
  CrowdStrikeSecretB:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CrowdStrike Credentials
      Name: !Join
        - '-'
        - - CrowdStrikeAPISecret
          - !Ref OUB
      SecretString:
        Fn::Join:
          - ''
          - - '{"FalconClientId":"'
            - Ref: "FalconClientIdB"
            - '","FalconSecret": "'
            - Ref: FalconSecretB
            - '","FalconCloud": "'
            - Ref: FalconCloudB
            - '"}'
  CrowdStrikeSecretC:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CrowdStrike Credentials
      Name: !Join
        - '-'
        - - CrowdStrikeAPISecret
          - !Ref OUC
      SecretString:
        Fn::Join:
          - ''
          - - '{"FalconClientId":"'
            - Ref: "FalconClientIdC"
            - '","FalconSecret": "'
            - Ref: FalconSecretC
            - '","FalconCloud": "'
            - Ref: FalconCloudC
            - '"}'
  CrowdStrikeSecretD:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CrowdStrike Credentials
      Name: !Join
        - '-'
        - - CrowdStrikeAPISecret
          - !Ref OUD
      SecretString:
        Fn::Join:
          - ''
          - - '{"FalconClientId":"'
            - Ref: "FalconClientIdD"
            - '","FalconSecret": "'
            - Ref: FalconSecretD
            - '","FalconCloud": "'
            - Ref: FalconCloudD
            - '"}'
  CrowdStrikeSecretE:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CrowdStrike Credentials
      Name: !Join
        - '-'
        - - CrowdStrikeAPISecret
          - !Ref OUE
      SecretString:
        Fn::Join:
          - ''
          - - '{"FalconClientId":"'
            - Ref: "FalconClientIdE"
            - '","FalconSecret": "'
            - Ref: FalconSecretE
            - '","FalconCloud": "'
            - Ref: FalconCloudE
            - '"}'
  CrowdStrikeSecretF:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CrowdStrike Credentials
      Name: !Join
        - '-'
        - - CrowdStrikeAPISecret
          - !Ref OUF
      SecretString:
        Fn::Join:
          - ''
          - - '{"FalconClientId":"'
            - Ref: "FalconClientIdF"
            - '","FalconSecret": "'
            - Ref: FalconSecretF
            - '","FalconCloud": "'
            - Ref: FalconCloudF
            - '"}'
  CrowdStrikeSecretG:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CrowdStrike Credentials
      Name: !Join
        - '-'
        - - CrowdStrikeAPISecret
          - !Ref OUG
      SecretString:
        Fn::Join:
          - ''
          - - '{"FalconClientId":"'
            - Ref: "FalconClientIdG"
            - '","FalconSecret": "'
            - Ref: FalconSecretG
            - '","FalconCloud": "'
            - Ref: FalconCloudG
            - '"}'
